<a href="https://colab.research.google.com/github/uday-kumar-1996/coding-practice/blob/main/coding_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
new_arr=arr[0:2,0:]
print(new_arr)


[[1 2 3]
 [4 5 6]]


In [ ]:
a=[1,2,3,4,5]
b=[6,7,8,9,10]
c=a+b
print(c)



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
new_arr=arr[0:2,1:]
new_arr



array([[2, 3],
       [5, 6]])

In [ ]:
arr[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[:1]

array([[1, 2, 3]])

In [ ]:
def fab(n):
  if n<=1:
    return n
  else:
    return fab(n-1)+fab(n-2)
fab(7)

13

In [ ]:
def fab(n):
  if n<=1:
    return 1
  else:
    return fab(n-1)+fab(n-2)
fab(7)

21

In [ ]:
def subsequences(arr,index,ans):
  if index==len(arr):
    print(ans)
    return
    subsequences(arr,index+1,ans)
    subsequences(arr,index+1,ans+str(arr[index]))

subsequences([1,2,3],0,"")


In [ ]:
a=[1,[2,3],[4,[5,6]],7]
b=len(a[2][1][0:1:2])
print(b)


1


In [ ]:
a=list(map(int,input().split()))
print(a)

22 33 44 55 66 77
[22, 33, 44, 55, 66, 77]


In [1]:
def sum_natural_numbers(n):
    if n == 1:
        return 1
    else:
        return n + sum_natural_numbers(n-1)

num = int(input("Enter a number: "))

if num <= 0:
    print("Invalid input. Please enter a positive integer.")
else:
    print("The sum of natural numbers up to", num, "is", sum_natural_numbers(num))


Enter a number: 15
The sum of natural numbers up to 15 is 120


In [4]:

def tribonacci(n):
    if n == 0 or n == 1:
        return 0
    elif n == 2:
        return 1
    else:
        return tribonacci(n-1) + tribonacci(n-2) + tribonacci(n-3)

num = int(input("Enter a number: "))

if num < 0:
    print("Invalid input. Please enter a non-negative integer.")
else:
    print("The", num, "th term in the Tribonacci sequence is", tribonacci(num))

Enter a number: 6
The 6 th term in the Tribonacci sequence is 7


In [5]:
def permutations(s):
    if len(s) == 0:
        return []
    elif len(s) == 1:
        return [s]
    else:
        result = []
        for i in range(len(s)):
            remaining = s[:i] + s[i+1:]
            perms = permutations(remaining)
            for perm in perms:
                result.append(s[i] + perm)

        return result
s = input("Enter a string: ")

print("All possible permutations of", s, "are:")
print(permutations(s))

Enter a string: abc
All possible permutations of abc are:
['abc', 'acb', 'bac', 'bca', 'cab', 'cba']
